name: placetalk
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  auto_route: ^7.8.0
  bloc: ^8.1.2
  dropdown_button2: ^2.3.7
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_markdown: ^0.6.17+1
  flutter_naver_map: ^1.0.2
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  geolocator: ^9.0.2
  http: ^1.1.0
  intl: ^0.18.1
  kakao_flutter_sdk_user: ^1.5.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.0
  build_runner: ^2.4.6


flutter:
  uses-material-design: true
  assets:
  - assets/logos/logo.svg
  - assets/logos/event_marker.svg
  - assets/images/profile.svg
  - assets/images/send.svg
  - assets/images/kakao_login.png
  - assets/images/profile.png
  - assets/images/always_marker.png
  - assets/images/moment_marker.png
  - assets/images/booth_marker.png
  - assets/images/concert.png
  - assets/images/festival.png
  - assets/images/local.png
  - assets/images/univ.png
  - assets/images/space.png
  - assets/images/leisure.png
  - assets/images/store.png
  - assets/images/home.png
  - assets/images/join.png
  - assets/images/explore.png
  - assets/images/store.png
  - assets/images/feed.png
  - assets/images/mypage.png

  fonts:
  - family: Pretendard
    fonts:
    - asset: assets/fonts/Pretendard-Black.otf
      weight: 900
    - asset: assets/fonts/Pretendard-ExtraBold.otf
      weight: 800
    - asset: assets/fonts/Pretendard-Bold.otf
      weight: 700
    - asset: assets/fonts/Pretendard-SemiBold.otf
      weight: 600
    - asset: assets/fonts/Pretendard-Medium.otf
      weight: 500
    - asset: assets/fonts/Pretendard-Regular.otf
      weight: 400
    - asset: assets/fonts/Pretendard-Light.otf
      weight: 300
    - asset: assets/fonts/Pretendard-ExtraLight.otf
      weight: 200
    - asset: assets/fonts/Pretendard-Thin.otf
      weight: 100
